accounts:
  - name: alice
    coins: ["100000000uatom", "100000000000000000000aphoton"]
  - name: bob
    coins: ["5000000000000tel1"]
validator:
  name: alice
  staked: "100000000000000000000tel1"
faucet:
  name: bob 
  coins: ["10tel1"]
build:
  binary: "tgenesisd"
init:
  home: "$HOME/.tgenesis"
  app:
    evm-rpc:
      address: "0.0.0.0:8545"     # change the JSON-RPC address and port
      ws-address: "0.0.0.0:8546"  # change the JSON-RPC websocket address and port
genesis:
  chain_id: "tgenesis_29-2"
  app_state:
    staking:
      params:
        bond_denom: "tel1"
    mint:
      params:
        mint_denom: "tel1"
    crisis:
      constant_fee:
        denom: "tel1"
    gov:
      deposit_params:
        min_deposit:
          - amount: "10000000"
            denom: "tel1"
    evm:
      params:
        evm_denom: "tel1"
